import ContactForm from "../../components/ContactForm";
import PageHero from "../../components/PageHero";
import SiteFooter from "../../components/SiteFooter";
import SiteHeader from "../../components/SiteHeader";

export default function ContactPage() {
  return <main>
    <SiteHeader />
    <PageHero eyebrow="CONTACT GUJARATI COMMUNITY IITG" title={<>Let us make<br /><em>space for you.</em></>} copy="Ask a question, share an idea, contribute to the archive or find your way into the community." image="/community/gallery/garba-crowd.jpg" />
    <section className="contact-page"><div className="contact-copy"><p className="eyebrow">FIND US</p><h2>Indian Institute of Technology Guwahati.</h2><p>Guwahati, Assam 781039. We meet across campus for events, planning sessions and celebrations.</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Indian+Institute+of+Technology+Guwahati" target="_blank" rel="noreferrer">Open in Google Maps <span>↗</span></a><div className="contact-cards"><article><p>EMAIL</p><a href="mailto:gujaraticommunityiitg@gmail.com">gujaraticommunityiitg@gmail.com</a></article><article><p>STUDENT COORDINATOR</p><b>Viraj Nagariya</b><a href="tel:+917202894219">+91 72028 94219</a><span>For all queries, ideas and collaboration requests, please contact him.</span></article></div></div><div className="map-wrap"><iframe title="IIT Guwahati location" src="https://www.google.com/maps?q=Indian%20Institute%20of%20Technology%20Guwahati&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></section>
    <section className="contact-form-section"><div><p className="eyebrow">WRITE TO US</p><h2>Every question gets a <em>home.</em></h2><p className="section-copy">Your note is saved in the community’s private inquiry database and forwarded to gujaraticommunityiitg@gmail.com.</p></div><ContactForm /></section>
    <section className="google-form-section"><div className="section-heading"><div><p className="eyebrow">CONNECT WITH GARBARAAS &amp; GUJARATI COMMUNITY IITG</p><h2>Connect with the GarbaRaas &amp; Gujarati Community <em>at IITG.</em></h2></div><p className="section-copy">Fill out the form to stay updated about our events and news.</p></div><a className="button dark" href="https://forms.gle/i3boJXUBKqv64x1h6" target="_blank" rel="noreferrer">Open the Google Form directly <span>↗</span></a></section>
    <section className="social-links-section"><p className="eyebrow">STAY CONNECTED</p><h2>Keep the circle <em>close.</em></h2><p className="social-intro">Thank you for taking the time to be part of the GarbaRaas IITG family.</p><div className="social-links-grid"><a href="https://chat.whatsapp.com/GbF45cYMvj1C5gxbIif9lK" target="_blank" rel="noreferrer"><span>FOR OUR GUJARATI MEMBERS</span><b>Gujarati Community WhatsApp Group <i className="arrow-glyph" aria-hidden="true" /></b></a><a href="https://chat.whatsapp.com/Ho3hFJix1S7JTDa7ih56ij" target="_blank" rel="noreferrer"><span>FOR EVERYONE</span><b>GarbaRaas IITG Family WhatsApp Group <i className="arrow-glyph" aria-hidden="true" /></b></a><a href="https://www.instagram.com/garbaraas_iitg" target="_blank" rel="noreferrer"><span>FOLLOW OUR UPDATES</span><b>Instagram @garbaraas_iitg <i className="arrow-glyph" aria-hidden="true" /></b></a></div></section>
    <section className="join-contribution"><p className="eyebrow">CONTRIBUTIONS AND DONATIONS</p><h2>For any contribution, please reach out to us.</h2><p>For donations, sponsorships or material support, contact the community team first. Verified contribution details are shared privately so that financial information is never published on the website.</p><a className="button dark" href="mailto:gujaraticommunityiitg@gmail.com">Email the community <span>↗</span></a></section>
    <SiteFooter />
  </main>;
}
