"use client";

import { useState } from "react";

const areas = ["Placements and careers", "Internships", "Academics", "Higher studies", "Research", "Settling into IITG", "Leadership and community work"];
const initialForm = { name: "", email: "", phone: "", programme: "", graduationYear: "", organisation: "", areas: [], note: "", consent: false, website: "" };

export default function MentorshipForm({ role }) {
  const [form, setForm] = useState(initialForm);
  const [status, setStatus] = useState({ type: "idle", message: "" });
  const set = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const toggleArea = (area) => set("areas", form.areas.includes(area) ? form.areas.filter((item) => item !== area) : [...form.areas, area]);
  const submit = async (event) => { event.preventDefault(); setStatus({ type: "loading", message: "Saving your interest…" }); try { const response = await fetch("/api/mentorship", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, role }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to save your interest."); setForm(initialForm); setStatus({ type: "success", message: "Thank you. The community team will review the next mentorship cycle and contact you directly." }); } catch (error) { setStatus({ type: "error", message: error.message }); } };
  return <form className="mentorship-form" onSubmit={submit}><div className="mentorship-form-grid"><label>Full name<input required value={form.name} onChange={(event) => set("name", event.target.value)} /></label><label>Email address<input required type="email" value={form.email} onChange={(event) => set("email", event.target.value)} /></label><label>Phone number <span>optional</span><input type="tel" value={form.phone} onChange={(event) => set("phone", event.target.value)} /></label><label>{role === "mentor" ? "Organisation / current role" : "Programme and department"}<input value={role === "mentor" ? form.organisation : form.programme} onChange={(event) => set(role === "mentor" ? "organisation" : "programme", event.target.value)} /></label><label>{role === "mentor" ? "Graduation year" : "Expected graduation year"}<input inputMode="numeric" value={form.graduationYear} onChange={(event) => set("graduationYear", event.target.value)} /></label></div><fieldset><legend>What would you like to talk about?</legend><div className="mentorship-area-list">{areas.map((area) => <label key={area}><input type="checkbox" checked={form.areas.includes(area)} onChange={() => toggleArea(area)} /> {area}</label>)}</div></fieldset><label>Anything the team should know? <span>optional</span><textarea rows="5" value={form.note} onChange={(event) => set("note", event.target.value)} placeholder={role === "mentor" ? "Your experience, availability or preferred kind of conversation." : "What you are hoping to understand or work through."} /></label><label className="mentorship-consent"><input type="checkbox" required checked={form.consent} onChange={(event) => set("consent", event.target.checked)} /> I’m happy for the Gujarati Community IITG team to contact me about mentorship. My details will not be published publicly.</label><label className="honeypot" aria-hidden="true">Leave empty<input tabIndex="-1" autoComplete="off" value={form.website} onChange={(event) => set("website", event.target.value)} /></label><button className="button dark" disabled={status.type === "loading"}>{status.type === "loading" ? "Saving…" : role === "mentor" ? "Offer mentorship" : "Find a mentor"}<span>↗</span></button>{status.type !== "idle" && <p className={`form-status ${status.type}`}>{status.message}</p>}</form>;
}
